src/main/java/com/pixeon/sistemaa/model/Clinica.java
package com.pixeon.sistemaa.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

@Entity
@Table(name = "clinica")
public class Clinica {
	
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;	
	private String nome;
	private String endereco;	
	
	@OneToOne
	@OnDelete(action=OnDeleteAction.CASCADE)
	private ClinicaServicoX clinicaServico;
	
	@ManyToOne
	private ClinicaCliente clinicaCliente;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getEndereco() {
		return endereco;
	}
	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}
	public ClinicaServicoX getClinicaServico() {
		return clinicaServico;
	}
	public void setClinicaServico(ClinicaServicoX clinicaServico) {
		this.clinicaServico = clinicaServico;
	}
	
	public ClinicaCliente getClinicaCliente() {
		return clinicaCliente;
	}
	public void setClinicaCliente(ClinicaCliente clinicaCliente) {
		this.clinicaCliente = clinicaCliente;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((clinicaCliente == null) ? 0 : clinicaCliente.hashCode());
		result = prime * result
				+ ((clinicaServico == null) ? 0 : clinicaServico.hashCode());
		result = prime * result
				+ ((endereco == null) ? 0 : endereco.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Clinica other = (Clinica) obj;
		if (clinicaCliente == null) {
			if (other.clinicaCliente != null)
				return false;
		} else if (!clinicaCliente.equals(other.clinicaCliente))
			return false;
		if (clinicaServico == null) {
			if (other.clinicaServico != null)
				return false;
		} else if (!clinicaServico.equals(other.clinicaServico))
			return false;
		if (endereco == null) {
			if (other.endereco != null)
				return false;
		} else if (!endereco.equals(other.endereco))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}		

}

src/main/java/com/pixeon/sistemaa/model/ClinicaCliente.java
package com.pixeon.sistemaa.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.pixeon.sistemaa.web.util.URLConfigUtil;

@Entity
@Table(name = "clinica_cliente")
public class ClinicaCliente implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;	
	
	private String dominio;
	private String porta;
	private String caminhoContexto;
	private String caminhoVisualizador;
	
	private String dominioServicoParametro;
	private String portaServicoParametro;		
	private String contextoServicoParametro;	
	private String recursoServicoParametro;
	private String pacienteParametroNome;
	private String exameParametroNome;
	private String pacienteParametroValor;
	private String exameParametroValor;
	
	public String getCaminhoBase() {
		return URLConfigUtil.montaContextoURL(dominio, porta, caminhoContexto, caminhoVisualizador);
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDominio() {
		return dominio;
	}
	public void setDominio(String dominio) {
		this.dominio = dominio;
	}
	public String getPorta() {
		return porta;
	}
	public void setPorta(String porta) {
		this.porta = porta;
	}
	public String getCaminhoContexto() {
		return caminhoContexto;
	}
	public void setCaminhoContexto(String caminhoContexto) {
		this.caminhoContexto = caminhoContexto;
	}
	public String getCaminhoVisualizador() {
		return caminhoVisualizador;
	}
	public void setCaminhoVisualizador(String caminhoVisualizador) {
		this.caminhoVisualizador = caminhoVisualizador;
	}
	public String getDominioServicoParametro() {
		return dominioServicoParametro;
	}
	public void setDominioServicoParametro(String dominioServicoParametro) {
		this.dominioServicoParametro = dominioServicoParametro;
	}
	public String getPortaServicoParametro() {
		return portaServicoParametro;
	}
	public void setPortaServicoParametro(String portaServicoParametro) {
		this.portaServicoParametro = portaServicoParametro;
	}
	public String getContextoServicoParametro() {
		return contextoServicoParametro;
	}
	public void setContextoServicoParametro(String contextoServicoParametro) {
		this.contextoServicoParametro = contextoServicoParametro;
	}
	public String getRecursoServicoParametro() {
		return recursoServicoParametro;
	}
	public void setRecursoServicoParametro(String recursoServicoParametro) {
		this.recursoServicoParametro = recursoServicoParametro;
	}
	public String getPacienteParametroNome() {
		return pacienteParametroNome;
	}
	public void setPacienteParametroNome(String pacienteParametroNome) {
		this.pacienteParametroNome = pacienteParametroNome;
	}
	public String getExameParametroNome() {
		return exameParametroNome;
	}
	public void setExameParametroNome(String exameParametroNome) {
		this.exameParametroNome = exameParametroNome;
	}
	public String getPacienteParametroValor() {
		return pacienteParametroValor;
	}
	public void setPacienteParametroValor(String pacienteParametroValor) {
		this.pacienteParametroValor = pacienteParametroValor;
	}
	public String getExameParametroValor() {
		return exameParametroValor;
	}
	public void setExameParametroValor(String exameParametroValor) {
		this.exameParametroValor = exameParametroValor;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((caminhoContexto == null) ? 0 : caminhoContexto.hashCode());
		result = prime
				* result
				+ ((caminhoVisualizador == null) ? 0 : caminhoVisualizador
						.hashCode());
		result = prime
				* result
				+ ((contextoServicoParametro == null) ? 0
						: contextoServicoParametro.hashCode());
		result = prime * result + ((dominio == null) ? 0 : dominio.hashCode());
		result = prime
				* result
				+ ((dominioServicoParametro == null) ? 0
						: dominioServicoParametro.hashCode());
		result = prime
				* result
				+ ((exameParametroNome == null) ? 0 : exameParametroNome
						.hashCode());
		result = prime
				* result
				+ ((exameParametroValor == null) ? 0 : exameParametroValor
						.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime
				* result
				+ ((pacienteParametroNome == null) ? 0 : pacienteParametroNome
						.hashCode());
		result = prime
				* result
				+ ((pacienteParametroValor == null) ? 0
						: pacienteParametroValor.hashCode());
		result = prime * result + ((porta == null) ? 0 : porta.hashCode());
		result = prime
				* result
				+ ((portaServicoParametro == null) ? 0 : portaServicoParametro
						.hashCode());
		result = prime
				* result
				+ ((recursoServicoParametro == null) ? 0
						: recursoServicoParametro.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClinicaCliente other = (ClinicaCliente) obj;
		if (caminhoContexto == null) {
			if (other.caminhoContexto != null)
				return false;
		} else if (!caminhoContexto.equals(other.caminhoContexto))
			return false;
		if (caminhoVisualizador == null) {
			if (other.caminhoVisualizador != null)
				return false;
		} else if (!caminhoVisualizador.equals(other.caminhoVisualizador))
			return false;
		if (contextoServicoParametro == null) {
			if (other.contextoServicoParametro != null)
				return false;
		} else if (!contextoServicoParametro
				.equals(other.contextoServicoParametro))
			return false;
		if (dominio == null) {
			if (other.dominio != null)
				return false;
		} else if (!dominio.equals(other.dominio))
			return false;
		if (dominioServicoParametro == null) {
			if (other.dominioServicoParametro != null)
				return false;
		} else if (!dominioServicoParametro
				.equals(other.dominioServicoParametro))
			return false;
		if (exameParametroNome == null) {
			if (other.exameParametroNome != null)
				return false;
		} else if (!exameParametroNome.equals(other.exameParametroNome))
			return false;
		if (exameParametroValor == null) {
			if (other.exameParametroValor != null)
				return false;
		} else if (!exameParametroValor.equals(other.exameParametroValor))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (pacienteParametroNome == null) {
			if (other.pacienteParametroNome != null)
				return false;
		} else if (!pacienteParametroNome.equals(other.pacienteParametroNome))
			return false;
		if (pacienteParametroValor == null) {
			if (other.pacienteParametroValor != null)
				return false;
		} else if (!pacienteParametroValor.equals(other.pacienteParametroValor))
			return false;
		if (porta == null) {
			if (other.porta != null)
				return false;
		} else if (!porta.equals(other.porta))
			return false;
		if (portaServicoParametro == null) {
			if (other.portaServicoParametro != null)
				return false;
		} else if (!portaServicoParametro.equals(other.portaServicoParametro))
			return false;
		if (recursoServicoParametro == null) {
			if (other.recursoServicoParametro != null)
				return false;
		} else if (!recursoServicoParametro
				.equals(other.recursoServicoParametro))
			return false;
		return true;
	}	

}

src/main/java/com/pixeon/sistemaa/web/ClinicaBean.java
package com.pixeon.sistemaa.web;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

import com.pixeon.sistemaa.model.Clinica;
import com.pixeon.sistemaa.model.ClinicaCliente;
import com.pixeon.sistemaa.model.ClinicaServicoX;
import com.pixeon.sistemaa.service.ClinicaService;
import com.pixeon.sistemaa.web.util.MensagemUtil;

@ManagedBean(name = "clinicaBean")
@RequestScoped
public class ClinicaBean {
	
	@Inject
	private ClinicaService clinicaService;	
	
	private Clinica clinica;
	private ClinicaServicoX clinicaServico;
	private ClinicaCliente clinicaCliente;
	private List<Clinica> clinicas;
	private List<ClinicaCliente> visualizadores;
	private Integer visualizadorCodigo;
	
	public ClinicaBean(){		
	}
	
	public ClinicaBean(ClinicaService clinicaService){
		this.clinicaService = clinicaService;
	}	
	
	@PostConstruct
	public void init(){
		clinica = new Clinica();
		clinicaServico = new ClinicaServicoX();
		clinicaCliente = new ClinicaCliente();
	}
	
	public String editar(){		
		return "clinica_edicao";
	}
	
	public String salvar(){			
		this.clinica.setClinicaServico(this.clinicaServico);
		
		ClinicaCliente visualizador = clinicaService.carregarVisualizador(visualizadorCodigo);
		this.clinica.setClinicaCliente(visualizador);				
		
		if(this.clinica.getId() == null || this.clinica.getId() == 0){			
			clinicaService.salvar(this.clinica);			
		} else {
			clinicaService.atualizar(this.clinica);
		}		
		MensagemUtil.adicionaMensagem("Clinica salva com sucesso.");
		return "clinicas?faces-redirect=true";
	}
	
	public String salvarCliente(){			
		this.clinica.setClinicaCliente(this.clinicaCliente);
		clinicaService.salvarCliente(clinica);		
		MensagemUtil.adicionaMensagem("Cliente/Visualizador da Clinica salvo com sucesso.");
		return "clinicas?faces-redirect=true";
	}
	
	public String excluir(){		
		clinicaService.remover(this.clinica);
		this.clinica = new Clinica();
		this.clinicas = null;
		MensagemUtil.adicionaMensagem("Clinica removida com sucesso.");		
		return null;
	}
	
	public void listarClinicas(){		
		clinicas = clinicaService.listar();		
	}	
	
	public void listarVisualizadores(){		
		visualizadores = clinicaService.listarVisualizadores();		
	}	

	public List<Clinica> getClinicas() {	
		if(clinicas == null){
			listarClinicas();
		}
		return clinicas;
	}

	public void setClinicas(List<Clinica> clinicas) {
		this.clinicas = clinicas;
	}	
	
	public List<ClinicaCliente> getVisualizadores() {
		if(visualizadores == null){
			listarVisualizadores();
		}
		return visualizadores;
	}

	public void setVisualizadores(List<ClinicaCliente> visualizadores) {
		this.visualizadores = visualizadores;
	}

	public Clinica getClinica() {
		return clinica;
	}

	public void setClinica(Clinica clinica) {
		this.clinica = clinica;
	}

	public ClinicaServicoX getClinicaServico() {
		return clinicaServico;
	}

	public void setClinicaServico(ClinicaServicoX clinicaServico) {
		this.clinicaServico = clinicaServico;
	}

	public ClinicaCliente getClinicaCliente() {
		return clinicaCliente;
	}

	public void setClinicaCliente(ClinicaCliente clinicaCliente) {
		this.clinicaCliente = clinicaCliente;
	}

	public Integer getVisualizadorCodigo() {
		return visualizadorCodigo;
	}

	public void setVisualizadorCodigo(Integer visualizadorCodigo) {
		this.visualizadorCodigo = visualizadorCodigo;
	}	
	
}

src/main/java/com/pixeon/sistemaa/web/ExameBean.java
package com.pixeon.sistemaa.web;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import com.pixeon.sistemaa.model.ClinicaCliente;
import com.pixeon.sistemaa.model.ClinicaServicoX;
import com.pixeon.sistemaa.model.Exame;
import com.pixeon.sistemaa.model.Paciente;
import com.pixeon.sistemaa.service.ExameService;
import com.pixeon.sistemaa.web.util.MensagemUtil;
import com.pixeon.sistemaa.web.util.URLConfigUtil;

@ManagedBean(name = "exameBean")
@ViewScoped
public class ExameBean {
	
	@Inject
	private ExameService exameService;	
	
	private Exame exameSelecionado = new Exame();
	private Integer codigoPaciente;
	private List<Exame> examesDoPaciente;	
	
	public ExameBean(){		
	}
	
	public ExameBean(ExameService exameService){
		this.exameService = exameService;
	}
	
	public void buscarExamesPorPaciente(){
		Paciente paciente = new Paciente();		
		paciente.setId(this.codigoPaciente);
		examesDoPaciente = exameService.buscarExamesPorPaciente(paciente);		
	}
	
	public void visualizaImagem(){
		ClinicaServicoX servico = exameSelecionado.getClinica().getClinicaServico();
		ClinicaCliente visualizador = exameSelecionado.getClinica().getClinicaCliente();
		
		String caminhoVisualizadorImagem = 
				URLConfigUtil.montaContextoURL(visualizador.getDominio(), 
						visualizador.getPorta(), visualizador.getCaminhoContexto(), visualizador.getCaminhoVisualizador());
		
		Map<String, Object> parametros = this.carregaParametrosVisualizador(servico, visualizador, exameSelecionado);
		caminhoVisualizadorImagem += URLConfigUtil.montaParametrosURL(parametros);
		
		ExternalContext context = FacesContext.getCurrentInstance().getExternalContext(); 
		
		try {			
			context.redirect(caminhoVisualizadorImagem);
		} catch (IOException e){			
			MensagemUtil.adicionaMensagem("Houve um erro desconhecido ao redirecionar para a imagem.");
		}	
	}	
	
	private Map<String, Object> carregaParametrosVisualizador(ClinicaServicoX servico, 
			ClinicaCliente visualizador, Exame exame){
		
		Map<String, Object> parametros = new HashMap<String, Object>();
		parametros.put(visualizador.getDominioServicoParametro(), servico.getDominio());
		parametros.put(visualizador.getPortaServicoParametro(), servico.getPorta());
		parametros.put(visualizador.getContextoServicoParametro(), servico.getCaminhoContexto());
		parametros.put(visualizador.getRecursoServicoParametro(), servico.getCaminhoRecurso());
		parametros.put(visualizador.getPacienteParametroNome(), servico.getPacienteParametro());
		parametros.put(visualizador.getExameParametroNome(), servico.getExameParametro());
		parametros.put(visualizador.getPacienteParametroValor(), exame.getPaciente().getId());
		parametros.put(visualizador.getExameParametroValor(), exame.getId());	
		
		return parametros;
	}

	public List<Exame> getExamesDoPaciente() {
		if(codigoPaciente != null && examesDoPaciente == null){
			buscarExamesPorPaciente();
		}
		return examesDoPaciente;
	}

	public void setExamesDoPaciente(List<Exame> examesDoPaciente) {
		this.examesDoPaciente = examesDoPaciente;
	}

	public Integer getCodigoPaciente() {
		return codigoPaciente;
	}

	public void setCodigoPaciente(Integer codigoPaciente) {
		this.codigoPaciente = codigoPaciente;
	}

	public Exame getExameSelecionado() {
		return exameSelecionado;
	}

	public void setExameSelecionado(Exame exameSelecionado) {
		this.exameSelecionado = exameSelecionado;
	}
	
}

src/main/webapp/publico/clinica_edicao.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
<ui:composition template="/templates/principal.xhtml">

	<ui:define name="titulo">
		SISTEMA A - Sistema centralizado de consulta de Exames
	</ui:define>

	<ui:define name="corpo">

		<f:view contentType="text/html">
			
			<h2>Cadastro de Clinicas</h2>
			
			<h:form id="voltar">
				<h:commandLink action="clinicas" value="Voltar" />
			</h:form>		
			
			<hr/>			

			<h:form id="cadastro">
				<h:messages />
				<h:inputHidden value="#{clinicaBean.clinica.id}" />	
				<h:inputHidden value="#{clinicaBean.clinicaServico.id}" />			

				<h:panelGrid columns="2">
					<h:outputLabel value="Nome:" for="nome" />
					<h:inputText id="nome" label="Nome"
						value="#{clinicaBean.clinica.nome}" size="80" required="true"
						requiredMessage="Favor informar o nome da Clinica"
						validatorMessage="O nome deve conter no minimo 5 caracteres">
						<f:validateLength minimum="5" maximum="80" />
					</h:inputText>

					<h:outputLabel value="Endereço:" for="endereco" />
					<h:inputText id="endereco" label="Endereço"
						value="#{clinicaBean.clinica.endereco}" size="80"
						required="false">						
					</h:inputText>				
				</h:panelGrid>

				<h:panelGroup>
					<fieldset>
						<legend>Clinica Serviço</legend>
						<h:panelGrid columns="4">
							<h:outputLabel value="Dominio: " for="dominio" />
							<h:inputText id="dominio" label="Dominio"
								value="#{clinicaBean.clinicaServico.dominio}" required="true"
								size="70" requiredMessage="O dominio deve ser informado" />

							<h:outputLabel value="Porta: " for="porta" />
							<h:inputText id="porta" label="Porta"
								value="#{clinicaBean.clinicaServico.porta}" size="6"
								maxlength="6">	
								<f:validateLongRange minimum="0" maximum="100000" />							
							</h:inputText>
							
							<h:outputLabel value="Contexto: " for="contexto" />
							<h:inputText id="contexto" label="Caminho do Contexto"
								value="#{clinicaBean.clinicaServico.caminhoContexto}" required="true"
								size="70" requiredMessage="O contexto deve ser informado" />
								
							<h:outputLabel value="Recurso: " for="recurso" />
							<h:inputText id="recurso" label="Recurso"
								value="#{clinicaBean.clinicaServico.caminhoRecurso}" required="true"
								size="70" requiredMessage="O recurso deve ser informado" />
								
							<h:outputLabel value="Paciente Parametro: " for="paciente" />
							<h:inputText id="paciente" label="Paciente Parametro"
								value="#{clinicaBean.clinicaServico.pacienteParametro}" required="true"
								size="70" requiredMessage="O Parametro do Paciente deve ser informado" />
								
							<h:outputLabel value="Exame Parametro: " for="exame" />
							<h:inputText id="exame" label="Exame Parametro"
								value="#{clinicaBean.clinicaServico.exameParametro}" required="true"
								size="70" requiredMessage="O Parametro do Exame deve ser informado" />
						</h:panelGrid>
					</fieldset>
				</h:panelGroup>	
				
				<h:panelGroup>
					<fieldset>
						<legend>Clinica Cliente/Visualizador</legend>
						<h:panelGrid columns="2">	
							<h:selectOneMenu value="#{clinicaBean.visualizadorCodigo}"								 
								rendered="#{!empty clinicaBean.visualizadores}">
								<f:selectItem itemValue="" itemLabel="Selecione"/>
								<f:selectItems 	value="#{clinicaBean.visualizadores}" var="visualizador"
									itemValue="#{visualizador.id}" itemLabel="#{visualizador.caminhoBase}"/>
							</h:selectOneMenu>		
						</h:panelGrid>
					</fieldset>
				</h:panelGroup>									
				
				<h:commandButton action="#{clinicaBean.salvar}" value="Salvar" />				
				<h:commandButton type="reset" value="Limpar" />
			</h:form>

		</f:view>

	</ui:define>
</ui:composition>
</html>

src/main/webapp/publico/clinicas.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
<ui:composition template="/templates/principal.xhtml">

	<ui:define name="titulo">
		SISTEMA A - Sistema centralizado de consulta de Exames
	</ui:define>

	<ui:define name="corpo">

		<f:view contentType="text/html">
			
			<h2>Cadastro de Clinicas</h2>
			
			<h:form id="nova">
				<table>
					<tr>
						<td>
							<h:commandButton action="clinica_edicao" value="Cadastrar nova" />											
						</td>
						<td>
							<h:commandButton action="cliente_edicao" value="Cadastrar Visualizador" />											
						</td>
					</tr>						
				</table>				
			</h:form>
			
			<br />
			<hr />
			<br />	
			<h:messages />		

			<h:form id="listagem">
				<h:dataTable border="1" cellpadding="2" cellspacing="0"
				 	value="#{clinicaBean.clinicas}" var="clinica"
					rendered="#{!empty clinicaBean.clinicas}">
					<h:column>
						<f:facet name="header">clinica</f:facet>
						#{clinica.nome}
					</h:column>
					<h:column>
						<f:facet name="header">Endereço</f:facet>
						#{clinica.endereco}
					</h:column>
					<h:column>
						<f:facet name="header">Editar</f:facet>
						<h:commandLink action="#{clinicaBean.editar}">
							<h:graphicImage library="imagens" name="editar16.png" style="border:0" />
							<f:setPropertyActionListener target="#{clinicaBean.clinica}" value="#{clinica}" />	
							<f:setPropertyActionListener target="#{clinicaBean.clinicaServico}" 
								value="#{clinica.clinicaServico}" />	
							<f:setPropertyActionListener target="#{clinicaBean.visualizadorCodigo}" value="#{clinica.clinicaCliente.id}" />											
						</h:commandLink>
					</h:column>
					<h:column>
						<f:facet name="header">Excluir</f:facet>
						<h:commandLink action="#{clinicaBean.excluir}"
							onclick="if (!confirm('Confirma a exclusão da clinica #{clinica.nome}?')) return false;">
							<h:graphicImage library="imagens" name="excluir16.png" style="border:0" />
							<f:setPropertyActionListener target="#{clinicaBean.clinica}" value="#{clinica}" />
						</h:commandLink>
					</h:column>
				</h:dataTable>
			</h:form>
			
		</f:view>

	</ui:define>
</ui:composition>
</html>

src/main/webapp/publico/exames.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
<ui:composition template="/templates/principal.xhtml">

	<ui:define name="titulo">
		SISTEMA A - Sistema centralizado de consulta de Exames
	</ui:define>

	<ui:define name="corpo">

		<f:view contentType="text/html">
			
			<h2>Consultar Exames por Paciente</h2>
			<h:messages />
			<h:form id="filtro">

				<h:panelGrid columns="3">
					<h:outputLabel value="Código de Identificação do Paciente: "
						for="codigoPaciente" />
					<h:inputText id="codigoPaciente"
						value="#{exameBean.codigoPaciente}" required="true" size="15"
						maxlength="45" />
					<h:commandButton value="Buscar"
						action="#{exameBean.buscarExamesPorPaciente}">
						<f:ajax execute="@this codigoPaciente" render=":filtro :listagem"></f:ajax>
					</h:commandButton>
				</h:panelGrid>

			</h:form>

			<h:form id="listagem">
				<h:dataTable border="1" cellpadding="2" cellspacing="0"
					value="#{exameBean.examesDoPaciente}" var="exame"
					rendered="#{!empty exameBean.examesDoPaciente}">
					<h:column>
						<f:facet name="header">Exame</f:facet>
				#{exame.nome}
			</h:column>
					<h:column>
						<f:facet name="header">Nome do Paciente</f:facet>
				#{exame.paciente.nome}
			</h:column>
					<h:column>
						<f:facet name="header">Nome do Solicitante</f:facet>				
					#{exame.solicitante}					
			</h:column>
					<h:column>
						<f:facet name="header">Clinica</f:facet>				
					#{exame.clinica.nome}					
			</h:column>
					<h:column>
						<f:facet name="header">Imagens</f:facet>
						<h:commandLink value="Ver Imagens"
							action="#{exameBean.visualizaImagem}" target="_blank">
							<f:setPropertyActionListener
								target="#{exameBean.exameSelecionado}" value="#{exame}" />
						</h:commandLink>
					</h:column>
				</h:dataTable>
			</h:form>
		</f:view>

	</ui:define>
</ui:composition>
</html>